Define 1D,2D,3D tensorflow Using Numpy And Pytorch

Using Numpy


In [1]:
import numpy as np

# 1D Tensor
a_np = np.array([1, 2, 3])

# 2D Tensor
b_np = np.array([[1, 2],
                 [3, 4]])

# 3D Tensor
c_np = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(a_np.shape, b_np.shape, c_np.shape)

(3,) (2, 2) (2, 2, 2)


Using Pytorch


In [39]:
import torch

# 1D Tensor
a_t = torch.tensor([1, 2, 3])

# 2D Tensor
b_t = torch.tensor([[2, 2],
                    [1, 4]])

# 3D Tensor
c_t = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(a_t.shape, b_t.shape, c_t.shape)


torch.Size([3]) torch.Size([2, 2]) torch.Size([2, 2, 2])


Operation Using Numpy

In [38]:
x = np.array([1, 2, 3])
y = np.array([2, 5, 10])

print(x + y)   # Addition
print(x - y)   # Subtraction
print(x * y)   # Multiplication
print(x / y)   # Division


[ 3  7 13]
[-1 -3 -7]
[ 2 10 30]
[0.5 0.4 0.3]


Using Pytorch

In [37]:
x = torch.tensor([10, 20, 30])
y = torch.tensor([2, 3, 1])

print(x + y)
print(x - y)
print(x * y)
print(x / y)


tensor([12, 23, 31])
tensor([ 8, 17, 29])
tensor([20, 60, 30])
tensor([ 5.0000,  6.6667, 30.0000])


Dot Product Using Numpy

In [36]:
a = np.array([1, 2, 3])
b = np.array([4, 2, 6])

print(np.dot(a, b))


26


Dot Product Using Pytorch

In [35]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([6, 7, 8])

print(torch.dot(a, b))

tensor(44)


Matrix Multiplication 2D Using Numpy

In [34]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 3],
              [7, 8]])

print(np.matmul(A, B))


[[19 19]
 [43 41]]


Matrix Multiplication 2D Using Pytorch

In [33]:
A = torch.tensor([[1, 2],
                  [3, 2]])
B = torch.tensor([[5, 6],
                  [7, 8]])

print(torch.matmul(A, B))
# or A @ B


tensor([[19, 22],
        [29, 34]])


Slicing Using Pytorch

In [32]:
x = torch.tensor([[10, 20, 30],
                  [20, 30, 40]])

print(x[0, 1])      # 20
print(x[:, 1])      # Column
print(x[1, :2])     # Row slice


tensor(20)
tensor([20, 30])
tensor([20, 30])


Boolean Masking Using Pytorch

In [10]:
x = torch.tensor([1, 2, 3, 4, 5])

mask = x > 3
print(x[mask])      # [4, 5]


tensor([4, 5])


Slicing Using Pytorch

In [11]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

sub = x[:2, :2]
print(sub)


tensor([[1, 2],
        [4, 5]])


Reshaping Tensors PyTorch: view(),reshape()

In [31]:
x = torch.tensor([1, 2, 3, 4, 5, 6])

print(x.view(2,3))
print(x.reshape(3, 2))


tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


.unsqueeze() – Add dimension

In [13]:
x = torch.tensor([1, 2, 3])

print(x.shape)
print(x.unsqueeze(0).shape)  # (1, 3)
print(x.unsqueeze(1).shape)  # (3, 1)


torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])


.squeeze() – Remove dimension

In [28]:
x = torch.tensor([[1, 2, 3]])
print(x.shape)
print(x.squeeze().shape)


torch.Size([1, 3])
torch.Size([3])


NumPy .reshape()

In [27]:
x = np.array([1, 2, 3, 4, 5, 6])
print(x.reshape(2, 3))


[[1 2 3]
 [4 5 6]]


Broadcasting (Different Shapes)

Using Numpy

In [20]:
A = np.array([[2, 2, 3],
              [4, 5, 3]])
B = np.array([10, 20, 30])

print(A + B)


[[12 22 33]
 [14 25 33]]


Using Pytorch

In [21]:
A = torch.tensor([[1, 4, 3],
                  [4, 5, 1]])
B = torch.tensor([10, 20, 30])

print(A + B)


tensor([[11, 24, 33],
        [14, 25, 31]])


Out-of-place (Creates new tensor)

In [22]:
x = torch.tensor([1, 6, 3])
y = x + 5

print(x)  # unchanged
print(y)


tensor([1, 6, 3])
tensor([ 6, 11,  8])


In-place (Modifies original tensor)

In [23]:
x = torch.tensor([1, 2, 4])
x.add_(5)

print(x)


tensor([6, 7, 9])
